# Change baseurl before deploy
baseurl = "https://riveroverflow.pages.dev"
title = "Riveroverflow"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "ko"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[comments]
    enabled = true
    provider = cusdis

    [cusdis]
    host = "https://cusdis.com"
    id = "7ca7b4c3-24c4-4e1e-93d5-a9e9b28224af"

[languages]
    [languages.en]
        languageCode = 'en-US'
        languageName = 'English'
        weight = 1
        [languages.en.params.sidebar]
            subtitle = 'Not just filling - overflowing'

    [languages.ko]
        languageCode = 'ko-KR'
        languageName = '한국어'
        weight = 2
        [languages.ko.params.sidebar]
            subtitle = '넘치게 채우기'


[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    id = 'G-NVWKFG7JEX'
